on:
  push:
    branches:
      - develop
      - main
      - master
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      release:
        description: 'Create a new release?'
        required: false
        default: 'false'

name: R-CMD-check

jobs:
  R-CMD-check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    timeout-minutes: 60
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: macOS-latest,   r: 'devel'}
          - {os: macOS-latest,   r: 'release'}
          - {os: macOS-latest,   r: 'oldrel'}
          - {os: windows-latest, r: 'devel'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'oldrel'}
          - {os: ubuntu-20.04,   r: 'devel'}
          - {os: ubuntu-20.04,   r: 'release'}
          - {os: ubuntu-20.04,   r: 'oldrel'}
    env:
      NOT_CRAN: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@main

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@master
      - uses: r-lib/actions/setup-tinytex@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@main
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Setup system environment for macOS
        if: runner.os == 'macOS'
        run: |
          set -x
          brew install curl || true
          brew install harfbuzz fribidi || true
          brew install git || true
          brew install glpk || true
          brew install icu4c || true
          brew install libgit2 || true
          brew install libpng || true
          brew install libtiff || true
          brew install libxml2 || true
          brew install make || true
          brew install netcdf || true
          brew install open-mpi || true
          brew install pandoc || true
          command -v gfortran >&/dev/null 2>&1 || ln -sv /usr/local/bin/gfortran-8 /usr/local/bin/gfortran ; ln -sv /usr/local/lib/gcc/8/* /usr/local/lib/ || true
        shell: bash

      - name: Setup system environment dor Windows
        if: runner.os == 'Windows'
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          echo "C:/rtools40/usr/bin;C:/rtools40/mingw64/bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
          pacman -Syu mingw-w64-x86_64-make --noconfirm
          g++ --version
          Get-Command g++ | Select-Object -ExpandProperty Definition
          mingw32-make --version
          Get-Command mingw32-make | Select-Object -ExpandProperty Definition
        shell: powershell

      - name: Setup system environment for Linux
        if: runner.os == 'Linux'
        run: |
          set -x
          sudo apt-get install -y clang-format || true
          sudo apt-get install -y git || true
          sudo apt-get install -y libcurl4-openssl-dev || true
          sudo apt-get install -y libgit2-dev || true
          sudo apt-get install -y libglpk-dev || true
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev || true
          sudo apt-get install -y libicu-dev || true
          sudo apt-get install -y libnetcdf-dev libnetcdff-dev || true
          sudo apt-get install -y libpng-dev || true
          sudo apt-get install -y libtiff-dev || true
          sudo apt-get install -y libxml2-dev || true
          sudo apt-get install -y make || true
          sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev || true
          sudo apt-get install -y pandoc || true
        shell: bash

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
          remotes::install_cran("curl")
          remotes::install_cran("devtools")
          remotes::install_cran("lintr")
          remotes::install_cran("pkgdown")
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("rmarkdown")
          remotes::install_cran("roxygen2")
          remotes::install_cran("sessioninfo")
          remotes::install_cran("styler")
          remotes::install_local(".")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Render documents
        if: runner.os == 'Linux'
        run: |
          if (grepl("devel", tolower(R.version$version.string)) && file.exists("README.Rmd")) rmarkdown::render("README.Rmd", output_format = "md_document")
          if (grepl("devel", tolower(R.version$version.string))) roxygen2::roxygenize()
        shell: Rscript {0}

      - name: Style and Format
        if: runner.os == 'Linux'
        run: |
          set -x
          if [[ $(Rscript -e 'cat(grepl("devel", tolower(R.version$version.string)))') == TRUE ]]; then
            Rscript -e 'styler::style_pkg()'
            find . -type f \( -name 'DESCRIPTION' -name "*.R" -o -name "*.stan" \) -exec sed -i -e 's/[ \t]*$//' {} \; || true
            find . -type f \( -name '*.h' -o -name '*.hpp' -o -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.cxx' \) -exec sed -i -e 's/[ \t]*$//' {} \; || true
            find . -type f \( -name '*.h' -o -name '*.hpp' -o -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.cxx' \) -exec clang-format -style=Google --verbose -i {} \; || true
          fi
        shell: bash

      - name: Commit changes
        if: runner.os == 'Linux'
        run: |
          set -x
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          if [[ $(Rscript -e 'cat(grepl("devel", tolower(R.version$version.string)))') == TRUE ]]; then
            git add README.md NAMESPACE man/\* || true
            git commit -m 'Roxygenize and render documents' || echo 'No changes to commit'
            find . -type f \( -name 'DESCRIPTION' -name "*.R" -o -name "*.stan" \) -exec git add {} \; || true
            git commit -m 'Formatting R code using styler' || echo 'No changes to commit'
            find . -type f \( -name '*.h' -o -name '*.hpp' -o -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.cxx' \) -exec git add {} \; || true
            git commit -m 'Formatting C/C++ code using clang-format' || echo 'No changes to commit'
            git push origin || echo "No changes to commit"
          fi
        shell: bash

      - name: Code analysis
        if: runner.os == 'Linux'
        run: |
          if (grepl("devel", tolower(R.version$version.string))) lintr::lint_package()
        shell: Rscript {0}

      - name: Test coverage
        if: runner.os == 'Linux'
        run: |
          if (grepl("devel", tolower(R.version$version.string))) covr::codecov(type = "all", line_exclusions = NULL, function_exclusions = NULL)
        shell: Rscript {0}

      - name: Deploy website
        if: runner.os == 'Linux'
        run: |
          set -x
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'if (grepl("devel", tolower(R.version$version.string))) pkgdown::deploy_to_branch(new_process = FALSE)'
        shell: bash

      - name: R CMD check
        env:
          _R_CHECK_CRAN_INCOMING_: false
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          _R_CHECK_DONTTEST_EXAMPLES_: false
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          set -x
          find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Build packages
        run: |
          src <- pkgbuild::build(".", dest_path = tempdir(), vignettes = FALSE, manual = FALSE, binary = FALSE)
          bin <- pkgbuild::build(".", dest_path = tempdir(), vignettes = FALSE, manual = FALSE, binary = TRUE)
          dir.create("build")
          file.copy(c(src, bin), "build")
        shell: Rscript {0}

      - name: Upload packages
        if: success()
        uses: actions/upload-artifact@main
        with:
          name: pkg-${{ matrix.config.os }}-${{ matrix.config.r }}
          path: build


  Release:
    timeout-minutes: 60
    if: startsWith(github.event.head_commit.message, '[release]') || github.event.inputs.release == 'true'
    runs-on: ubuntu-20.04

    needs: [R-CMD-check]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@main

      - name: Extract version
        run: |
          set -x
          echo "PACKAGE_VERSION=$(grep '^Version' DESCRIPTION  | sed 's/.*: *//')" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$(grep '^Package' DESCRIPTION  | sed 's/.*: *//')" >> $GITHUB_ENV
          echo "PACKAGE_SHA=$(git rev-parse --short HEAD | sed 's/.*: *//')" >> $GITHUB_ENV
        shell: bash

      - uses: actions/download-artifact@main
        with:
          path: pkg

      - name: List files
        run: |
          set -x
          echo ${{ env.PACKAGE_NAME }} ${{ env.PACKAGE_VERSION }}-${{ env.PACKAGE_SHA }}
          ls -R pkg
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}-${{ env.PACKAGE_SHA }}
          release_name: ${{ env.PACKAGE_NAME }} ${{ env.PACKAGE_VERSION }}-${{ env.PACKAGE_SHA }}
          draft: false
          prerelease: false

      - name: Upload source
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pkg/pkg-ubuntu-20.04-devel/${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}.tar.gz
          asset_name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload macOS binary (devel)
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pkg/pkg-macOS-devel-release/${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}.tgz
          asset_name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}_devel.tgz
          asset_content_type: application/gzip

      - name: Upload macOS binary (release)
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pkg/pkg-macOS-latest-release/${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}.tgz
          asset_name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}.tgz
          asset_content_type: application/gzip

      - name: Upload macOS binary (oldrel)
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pkg/pkg-macOS-latest-oldrel/${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}.tgz
          asset_name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}_oldrel.tgz
          asset_content_type: application/gzip

      - name: Upload Windows binary (devel)
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pkg/pkg-windows-latest-devel/${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}.zip
          asset_name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}_devel.zip
          asset_content_type: application/zip

      - name: Upload Windows binary (release)
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pkg/pkg-windows-latest-release/${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}.zip
          asset_name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Windows binary (oldrel)
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pkg/pkg-windows-latest-oldrel/${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}.zip
          asset_name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}_oldrel.zip
          asset_content_type: application/zip
